# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install jupyter and nbconvert
        run: |
          pip install jupyter
          pip install nbconvert

      - name: Make list
        run: |
          find . -name ipynb_checkpoints -prune -o -iname \*ipynb >> ipy_list.txt

      - name: Print names in the text file
        run: |
          while read p;
          do
            jupyter nbconvert  --clear-output --inplace "$p"
          done

      - name: Check local directory
        run: |
          rm ipy_list.txt

      - name: Recommit with clear notebooks
        run: |
          git add .
          git config --global user.email "github-action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Recommited with clean Notebooks" -a || echo "No changes to commit"
          git push origin


