# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Find local directory
        run: |
          pwd
          ls

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.1'

      - name: Install jupyter and nbconvert
        run: |
          pip install jupyter
          pip install nbconvert

      # hooks:
      # - id: jupyter-nb-clear-output
      #   name: jupyter-nb-clear-output
      #   files: \.ipynb$
      #   stages: [commit]
      #   language: system
      #   entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

      - name: Run jupyter clear
        files: \.ipynb$
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

      - name: Find ipynb files and create config
        run: |
          find . -name ipynb_checkpoints -prune -o -iname \*ipynb >> ipy_notbooks.txt

      - name: Clear Jupyter notebook output cells
        run: jupyter nbconvert  --clear-output --inplace

      - name: Cleanup files
        run: rm ipy_notbooks.text

      - name: Recommit with clear notebooks
        run: |
          git add .
          git config --global user.email "github-action@github.com"
          git config --global user.name "GitHub Action"
          git commit -m "Recommited with clean Notebooks" -a || echo "No changes to commit"
          git push


