# Run linting check on Jupyter notebooks.

name: OpenMDAO Book Workflow

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Remove push when finally merging.
  push:
    branches: [ main, artifact_update2]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # This job is called test_docs.
  test_docs:
    # Run on Ubuntu
    runs-on: ubuntu-latest

    steps:

      # TEMPORARY WHILE GITHUB FIXES THIS https://github.com/actions/virtual-environments/issues/3185
      - name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
        run: |
          echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install OpenMDAO Stack
        run: |
          echo "=============================================================";
          echo "Run #${GITHUB_RUN_NUMBER}";
          echo "Run ID: ${GITHUB_RUN_ID}";
          echo "Testing: ${GITHUB_REPOSITORY}";
          echo "Triggered by: ${GITHUB_EVENT_NAME}";
          echo "Initiated by: ${GITHUB_ACTOR}";
          echo "=============================================================";

          echo "=============================================================";
          echo "Create conda environment";
          echo "=============================================================";
          source $CONDA/etc/profile.d/conda.sh;
          echo $CONDA/bin >> $GITHUB_PATH;
          conda create -n OpenMDAO python=3.8 numpy=1.18 scipy=1.4 -q -y;
          conda activate OpenMDAO;

          echo "=============================================================";
          echo "Install PETSc";
          echo "=============================================================";
          conda install -c anaconda mpi4py -q -y;
          conda install -c conda-forge petsc=3.12 petsc4py -q -y;

          echo "=============================================================";
          echo "Install pyoptsparse";
          echo "=============================================================";

          git clone -q https://github.com/OpenMDAO/build_pyoptsparse;

          cd build_pyoptsparse;
          chmod 755 ./build_pyoptsparse.sh;
          ./build_pyoptsparse.sh -b "v2.1.5";
          cd ..;

          export LD_LIBRARY_PATH=$HOME/ipopt/lib;

          echo "=============================================================";
          echo "Install OpenMDAO";
          echo "=============================================================";
          cd ..;
          git clone -q https://github.com/OpenMDAO/OpenMDAO;
          cd OpenMDAO;
          pip install .[all];
          cd ../OpenMDAO_Book;

          echo "=============================================================";
          echo "Install packages for Notebooks.";
          echo "=============================================================";
          pip install matplotlib;
          pip install jupyter;
          pip install nbconvert;
          pip install testflo;
          pip install ipyparallel;

          echo "=============================================================";
          echo "List installed packages/versions";
          echo "=============================================================";
          conda list;

          echo "=============================================================";
          echo "Final additional setup to run MPI under notebooks.";
          echo "=============================================================";
          jupyter serverextension enable --py ipyparallel;
          ipython profile create --parallel --profile=mpi;
          echo "c.IPClusterEngines.engine_launcher_class = 'MPIEngineSetLauncher'" >> ~/.ipython/profile_mpi/ipcluster_config.py;
          echo "c.IPClusterStart.controller_launcher_class = 'MPIControllerLauncher'" >> ~/.ipython/profile_mpi/ipcluster_config.py;
          ipcluster start -n 2 --profile=mpi &
          sleep 12

          echo "=============================================================";
          echo "Run the tests.";
          echo "=============================================================";
          testflo -n 1

          echo "=============================================================";
          echo "Build the docs.";
          echo "=============================================================";
          ./build_all_docs.sh
          cd openmdao_book/_build
          tar -czvf ./openmdao_book.tar.gz html
          echo "=============================================================";
          echo "Operations Completed.";
          echo "=============================================================";

      - name: 'Upload Book'
        uses: actions/upload-artifact@v2
        with:
          name: openmdao_book
          path: openmdao_book/_build/html
          if-no-files-found: error
          retention-days: 7
